[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.flower]
    address = ":5555"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "tychot@bam.tech"
      storage = "/etc/traefik/acme/acme.json"
      [certificatesResolvers.letsencrypt.acme.httpChallenge]
        entryPoint = "web"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    
[http.routers]
  [http.routers.media]
    rule = "Host(`katago.tycoach.me`) && PathPrefix(`/media`)"
    entryPoints = ["web"]
    middlewares = ["redirect"]
    service = "nginx"
  [http.routers.media-secure]
    rule = "Host(`katago.tycoach.me`) && PathPrefix(`/media`)"
    entryPoints = ["web-secure"]
    service = "nginx"
    [http.routers.media-secure.tls]
      certResolver = "letsencrypt"
  [http.routers.web]
    rule = "Host(`katago.tycoach.me`)"
    entryPoints = ["web"]
    middlewares = ["redirect", "csrf"]
    service = "django"
  [http.routers.web-secure]
    rule = "Host(`katago.tycoach.me`)"
    entryPoints = ["web-secure"]
    middlewares = ["csrf"]
    service = "django"
    [http.routers.web-secure.tls]
      certResolver = "letsencrypt"
  [http.routers.flower]
    rule = "Host(`katago.tycoach.me`)"
    entryPoints = ["flower"]
    service = "flower"
    [http.routers.flower.tls]
      certResolver = "letsencrypt"

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"
    permanent = true
  [http.middlewares.csrf.headers]
    hostsProxyHeaders = ["X-CSRFToken"]

[http.services]
  [http.services.django.loadBalancer]
    [[http.services.django.loadBalancer.servers]]
      url = "http://django:5000"
  [http.services.nginx.loadBalancer]
    [[http.services.nginx.loadBalancer.servers]]
      url = "http://nginx:80"
  [http.services.flower.loadBalancer]
    [[http.services.flower.loadBalancer.servers]]
      url = "http://flower:5555"

[providers]
  [providers.file]    
    filename = "/etc/traefik/traefik.toml"
    watch = true
